### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by ghost** [loeck/local-server#11]
Tried to start the server but it didn't start.

**Atom Version**: 0.187.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [local-server](https://github.com/lohek/local-server) package, v0.1.0
### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At C:\Users\nicolae.surdu\.atom\packages\local-server\node_modules\express\node_modules\depd\index.js:414

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function.wrapfunction (C:\Users\nicolae.surdu\.atom\packages\local-server\node_modules\express\node_modules\depd\index.js:414:5)
  at Object.<anonymous> (C:\Users\nicolae.surdu\.atom\packages\local-server\node_modules\express\node_modules\send\index.js:156:47)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (C:\Users\nicolae.surdu\AppData\Local\atom\app-0.187.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\nicolae.surdu\.atom\packages\local-server\node_modules\express\lib\utils.js:16:12)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (C:\Users\nicolae.surdu\AppData\Local\atom\app-0.187.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\nicolae.surdu\.atom\packages\local-server\node_modules\express\lib\application.js:15:15)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (C:\Users\nicolae.surdu\AppData\Local\atom\app-0.187.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\nicolae.surdu\.atom\packages\local-server\node_modules\express\lib\express.js:7:13)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (C:\Users\nicolae.surdu\AppData\Local\atom\app-0.187.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\nicolae.surdu\.atom\packages\local-server\node_modules\express\index.js:2:18)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (C:\Users\nicolae.surdu\AppData\Local\atom\app-0.187.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at LocalServerView.module.exports.LocalServerView.startServer (C:\Users\nicolae.surdu\.atom\packages\local-server\lib\local-server-view.coffee:31:15)
  at C:\Users\nicolae.surdu\.atom\packages\local-server\lib\local-server-view.coffee:26:8
  at Server.onListen (C:\Users\nicolae.surdu\.atom\packages\local-server\node_modules\portfinder\lib\portfinder.js:49:5)
  at Server.g (events.js:202:16)
  at Server.emit (events.js:113:17)
  at net.js:1170:12
  at process._tickCallback (node.js:366:11)

```
### Commands

```
     -8:13.9 editor:move-to-end-of-word (atom-text-editor.editor)
     -6:43.0 open-on-github:blame (atom-text-editor.editor)
     -5:52.2 core:confirm (atom-text-editor.editor.mini)
     -0:31.3 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:09.8 local-server:start (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
local-server, v0.1.0

# Dev
No dev packages
```

**Comment by ghost** [comment]
Sorry. I see just now that basically everybody reported this :laughing:
