### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by lesmerleauxdurasdotcom** [loeck/local-server#5]
[Enter steps to reproduce below:]
1. Opened an HTML file
2. Pressed Ctrl+Alt+S (as indicated)

**Atom Version**: 0.176.0
**System**: linux 3.13.0-39-generic
**Thrown From**: [local-server](https://github.com/lohek/local-server) package, v0.1.0
### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /home/jeff/.atom/packages/local-server/node_modules/express/node_modules/depd/index.js:414

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function.wrapfunction (/home/jeff/.atom/packages/local-server/node_modules/express/node_modules/depd/index.js:414:5)
  at Object.<anonymous> (/home/jeff/.atom/packages/local-server/node_modules/express/node_modules/send/index.js:150:47)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/jeff/.atom/packages/local-server/node_modules/express/lib/utils.js:7:12)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/jeff/.atom/packages/local-server/node_modules/express/lib/application.js:6:15)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/jeff/.atom/packages/local-server/node_modules/express/lib/express.js:7:13)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/jeff/.atom/packages/local-server/node_modules/express/index.js:2:18)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at LocalServerView.module.exports.LocalServerView.startServer (/home/jeff/.atom/packages/local-server/lib/local-server-view.coffee:31:15)
  at /home/jeff/.atom/packages/local-server/lib/local-server-view.coffee:26:8
  at Server.onListen (/home/jeff/.atom/packages/local-server/node_modules/portfinder/lib/portfinder.js:49:5)
  at Server.g (events.js:199:16)
  at Server.emit (events.js:104:17)
  at net.js:1151:12
  at process._tickCallback (node.js:386:11)

```
### Commands

```
     -5:18.5 settings-view:open (atom-text-editor.editor)
 28x -4:28.9 core:backspace (atom-text-editor.editor.mini)
  2x -1:54.5 local-server:start (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
local-server, v0.1.0
minimap, v4.1.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by au-phiware** [comment]
### Steps to reproduce:
1. Opened an HTML file
2. Pressed Ctrl+Alt+Cmd+S

**Atom Version**: 0.187.0-abf368e
**System**: linux 3.17.8-gentoo-r1
**Thrown From**: [local-server](https://github.com/lohek/local-server) package, v0.1.0

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /home/corin/.atom/packages/local-server/node_modules/express/node_modules/depd/index.js:414

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function.wrapfunction (/home/corin/.atom/packages/local-server/node_modules/express/node_modules/depd/index.js:414:5)
  at Object.<anonymous> (/home/corin/.atom/packages/local-server/node_modules/express/node_modules/send/index.js:156:47)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/corin/.atom/packages/local-server/node_modules/express/lib/utils.js:16:12)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/corin/.atom/packages/local-server/node_modules/express/lib/application.js:15:15)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/corin/.atom/packages/local-server/node_modules/express/lib/express.js:7:13)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/corin/.atom/packages/local-server/node_modules/express/index.js:2:18)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at LocalServerView.module.exports.LocalServerView.startServer (/home/corin/.atom/packages/local-server/lib/local-server-view.coffee:31:15)
  at /home/corin/.atom/packages/local-server/lib/local-server-view.coffee:26:8
  at Server.onListen (/home/corin/.atom/packages/local-server/node_modules/portfinder/lib/portfinder.js:49:5)
  at Server.g (events.js:202:16)
  at Server.emit (events.js:113:17)
  at net.js:1170:12
  at process._tickCallback (node.js:366:11)

```

### Commands

```
     -7:44.9 window:toggle-dev-tools (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-atom-solarized-dark-ui)
     -5:20.5 core:confirm (atom-text-editor.editor.mini)
     -3:28.2 web-browser:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:37.1 core:confirm (atom-text-editor.editor.mini)
     -0:00.5 local-server:start (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-solarized-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-browser-webview, v0.6.0
atom-solarized-dark-ui, v0.25.0
emmet, v2.3.4
local-server, v0.1.0
vim-mode, v0.39.0
vim-surround, v0.4.2

# Dev
No dev packages
```
